{% set version = "3.3.1" %}

package:
  name: triqs_ctseg
  version: {{ version }}

source:
  url: https://github.com/TRIQS/ctseg/releases/download/{{ version }}/ctseg-{{ version }}.tar
  sha256: 4ad56742fd83eb4af199193b601d4b8ec160c3c3c81d5b18d1466b7171673510

build:
  number: 0
  skip: true  # [win or py<30]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - {{ mpi }}                              # [mpi == 'openmpi' and build_platform != target_platform]
  host:
    - triqs {{ '.'.join(version.split('.')[:2]) }}
    - libboost-headers
    - fftw                                   # [target_platform == 'osx-arm64']
    - hdf5
    - {{ mpi }}
    - libblas
    - liblapack
    - numpy
    - python
  run:
    - {{ pin_compatible("triqs", max_pin="x.x") }}
    - fftw                                   # [target_platform == 'osx-arm64']
    - hdf5
    - {{ mpi }}
    - libblas
    - liblapack
    - python

test:
  commands:
    - export OMPI_MCA_btl=self,tcp
    - export OMPI_MCA_plm=isolated
    - export OMPI_MCA_rmaps_base_oversubscribe=yes
    - export OMPI_MCA_btl_vader_single_copy_mechanism=none
    - export mpiexec="mpiexec --allow-run-as-root"
    - python -c "import triqs_ctseg"

about:
  home: https://triqs.github.io/ctseg
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: A segment picture impurity solver with spin-spin interactions

extra:
  recipe-maintainers:
    - Wentzell
    - Thoemi09
